import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { getAllPokemons } from "./api/pokemonApi";
interface Props {
  pokemons: [{ name: string }];
}
const Home: React.FC<Props> = (props) => {
  console.log(props.pokemons);
  return (
    <div>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Pokemon</h1>
        {!!props.pokemons &&
          props.pokemons.map((pokemon, i) => {
            return <p key={i}>{pokemon.name}</p>;
          })}
      </div>
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  const allPokemons = await getAllPokemons();
  return {
    props: {
      pokemons: allPokemons,
    },
  };
};
